#pragma once

namespace FarLight
{
	enum class MouseButtonCodes
	{
		FL_MOUSE_BUTTON_UNKNOWN = -1,
		FL_MOUSE_BUTTON_1 = 0,
		FL_MOUSE_BUTTON_2 = 1,
		FL_MOUSE_BUTTON_3 = 2,
		FL_MOUSE_BUTTON_4 = 3,
		FL_MOUSE_BUTTON_5 = 4,
		FL_MOUSE_BUTTON_6 = 5,
		FL_MOUSE_BUTTON_7 = 6,
		FL_MOUSE_BUTTON_8 = 7,
		FL_MOUSE_BUTTON_LAST = 8,
		FL_MOUSE_BUTTON_LEFT = 9,
		FL_MOUSE_BUTTON_RIGHT = 10,
		FL_MOUSE_BUTTON_MIDDLE = 11
	};
}